name: Build Rio Terminal Portable Binary with Patch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl tar pkg-config zip \
            git wget patchelf \
            rustc cargo \
            libxkbcommon-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev \
            libx11-dev libxcb1-dev libxkbcommon-x11-dev libwayland-dev \
            libfontconfig-dev

      - name: Download Rio Terminal source
        run: |
          mkdir -p ~/rio-build
          cd ~/rio-build
          wget "https://github.com/raphamorim/rio/archive/refs/tags/v0.1.12.tar.gz" -O rio-0.1.12.tar.gz
          tar -xzf rio-0.1.12.tar.gz

      - name: Apply patch to force black UI rendering
        run: |
          cd ~/rio-build/rio-0.1.12
          # Example patch: Replace gray with black in a hypothetical file
          echo "Patching source to force black UI elements..."
          # This is a placeholder; adjust based on actual file and line
          sed -i 's/Color { r: 0.5, g: 0.5, b: 0.5, a: 1.0 }/Color { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }/g' src/screen/tabs.rs || true
          # Add more sed commands or a .patch file if needed

      - name: Build Rio Terminal
        run: |
          cd ~/rio-build/rio-0.1.12
          cargo build --release

      - name: Install Rio to staging directory
        run: |
          mkdir -p ~/rio-install/usr/bin
          cp ~/rio-build/rio-0.1.12/target/release/rio ~/rio-install/usr/bin/rio-bin

      - name: Bundle all shared library dependencies
        run: |
          cd ~/rio-install
          mkdir -p usr/lib
          chmod +w usr/bin/rio-bin
          echo "Listing libraries required by rio:"
          ldd usr/bin/rio-bin
          ldd usr/bin/rio-bin | grep -o '/[^ ]*\.so[^ ]*' | sort -u | while read lib; do
            echo "Copying $lib"
            cp -v "$lib" usr/lib/ || { echo "Error: Failed to copy $lib"; exit 1; }
          done
          cp -v /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 usr/lib/ || { echo "Error: Failed to copy libfontconfig"; exit 1; }
          cp -v /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 usr/lib/ || { echo "Error: Failed to copy linker"; exit 1; }
          echo "Final library list in usr/lib:"
          ls -l usr/lib/

      - name: Ensure RPATH with patchelf
        run: |
          patchelf --force-rpath --set-rpath \$ORIGIN/../lib ~/rio-install/usr/bin/rio-bin

      - name: Create configuration file
        run: |
          mkdir -p ~/rio-install/usr/config
          cat > ~/rio-install/usr/config/rio.toml << EOF
          use-fork = false
          [colors]
          background = "#000000"
          foreground = "#00FFFF"
          cursor = "#9400D3"
          tabs = "#000000"
          tabs-active = "#000000"
          selection-foreground = "#00FFFF"
          selection-background = "#000000"
          black = "#000000"
          EOF
          chmod 644 ~/rio-install/usr/config/rio.toml
          cat ~/rio-install/usr/config/rio.toml

      - name: Create launcher script
        run: |
          cd ~/rio-install/usr/bin
          cat > rio << EOF
          #!/bin/bash
          DIR="\$(dirname "\$(realpath "\$0")")"
          "\$DIR/../lib/ld-linux-x86-64.so.2" --library-path "\$DIR/../lib" "\$DIR/rio-bin" --config-file "\$DIR/../config/rio.toml" "\$@"
          EOF
          chmod +x rio
          cat rio

      - name: Create zip file with binary and libraries
        run: |
          cd ~/rio-install
          zip -r ~/rio-0.1.12-portable.zip .

      - name: Generate SHA256 checksum
        run: |
          sha256sum ~/rio-0.1.12-portable.zip > ~/rio-0.1.12-portable.zip.sha256
          cat ~/rio-0.1.12-portable.zip.sha256

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: rio-portable
          path: |
            ~/rio-0.1.12-portable.zip
            ~/rio-0.1.12-portable.zip.sha256
